### ISSUE TITLE
Adding toDisplay and toValue callbacks

### ISSUE THREAD

**Issue by pmishev** [AuspeXeu/bootstrap-datetimepicker#11]
Do you currently have any plans to add such methods that allow displaying the datetime in the input in a different format than the one that is actually submitted (as documented here https://bootstrap-datepicker.readthedocs.io/en/latest/options.html#format)?

**Comment by AuspeXeu** [comment]
I don't, no. But you are more than welcome to file a PR :)

**Comment by AuspeXeu** [comment]
Closed due to inactivity
