### ISSUE TITLE
How do you use this datetimepicker in your own html+js files?

### ISSUE THREAD

**Issue by qhchen2** [AuspeXeu/bootstrap-datetimepicker#14]
The below instructions make no sense to me, as I have no experience with bootstrap.
I just need to know what js files to include in the html, and what html-elements to include, and what template code to include in the js. Why is that not in the documentation like with all the other datetimepickers?

```
Requires bootstrap's dropdown component (dropdowns.less) for some styles, and bootstrap's sprites (sprites.less and associated images) for arrows.

A standalone .css file (including necessary dropdown styles and alternative, text-based arrows) can be generated by running build/build_standalone.less through the lessc compiler:

$ lessc build/build_standalone.less > datetimepicker.css
```

**Comment by Lechucico** [comment]
You need to import the following files:

Bootstrap:
- bootstrap.min.css

Bootstrap-datetimepicker:
- bootstrap-datetimepicker.min.css
- bootstrap-datetimepicker.min.js

JQuery:
- jquery-3.3.1.min.js
