### ISSUE TITLE
Datetimepicker initial date 

### ISSUE THREAD

**Issue by Lechucico** [AuspeXeu/bootstrap-datetimepicker#17]
By default, datetimepicker initial date shows the following:

<img width="234" alt="image" src="https://user-images.githubusercontent.com/22009615/39199895-e60ea08a-47ea-11e8-9fff-a3331863b25b.png">

Why isn't today? I try to set it to today with this, but doesn't work:

```
<script>
$("#datetimepicker").datetimepicker({
    format: "dd/mm/yy hh:ii",
    autoclose: true,
    todayBtn: true,
    pickerPosition: "top-left",
    weekStart: "1",
    minView: "0",
    maxView: "2",
    todayHighlight: true,
    language: 'es',
    minuteStep: 15,
    initialDate: "2018-04-24"
});
</script>
```

**Comment by AuspeXeu** [comment]
If you don't give an `initialDate` it will default to `now`
