### ISSUE TITLE
Datetimepicker linked to another datetimepicker

### ISSUE THREAD

**Issue by Lechucico** [AuspeXeu/bootstrap-datetimepicker#18]
I have two datetimepicker.

The idea is that once selected the first one, the second one shows the same datetime plus 1 day.

For example: if clicked on 24-04-2018 on the first datetimepicker, the second one has to show 25-04-2018 without any interaction.

How I can do that?

**Comment by AuspeXeu** [comment]
https://github.com/AuspeXeu/bootstrap-datetimepicker#changedate

```
$('#datetimepicker').datetimepicker('setDate', data);
```
