### ISSUE TITLE
Is this compatible with Bootstrap 4?

### ISSUE THREAD

**Issue by henryonsoftware** [AuspeXeu/bootstrap-datetimepicker#25]
Is this repository compatible with Bootstrap 4?

**Comment by AuspeXeu** [comment]
No idea, haven't tried. Maybe you can give it a go? :)

**Comment by henryonsoftware** [comment]
@AuspeXeu  I just tried and it didn't compatible. Do you have any plan upgrade it to BT4?

**Comment by AuspeXeu** [comment]
Not really, I am quite short on time these days. But you can have a try if you want :)

**Comment by AuspeXeu** [comment]
Can you provide a jsfiddle to illustrate this?
https://jsfiddle.net/AuspeXeu/sqwwcjzu/

Maybe we can make it work :)

**Comment by henryonsoftware** [comment]
Sorry but I don't need to use it anymore. I used https://github.com/tempusdominus/bootstrap-4 instead.
