### ISSUE TITLE
onRenderHour ignore daysOfWeekDisabled and datesDisabled

### ISSUE THREAD

**Issue by jeromebon** [AuspeXeu/bootstrap-datetimepicker#27]
Even through daysOfWeekDisabled or datesDisabled is set it's possible to pick a disabled day, by doing the following:
- Pick the day before the disabled one.
- On the view to select the hour use the next arrow
- Then you are on the day supposed to be disabled and you can still pick an hour

Expected behavior: The hours for that day should be disabled

If it's actually a bug i can prepare a PR :)

**Comment by AuspeXeu** [comment]
Yes please :)
