### ISSUE TITLE
daysOfWeekDisabled is not working on sunday

### ISSUE THREAD

**Issue by pratyushdhanuka** [AuspeXeu/bootstrap-datetimepicker#5]
Fiddle : Please discard old link
Correct Link Fidlde [https://jsfiddle.net/sqwwcjzu/36/](url)

I am unable to set sunday as disabled
I want only Monday to come as allowed days of week, but I am unable to remove sunday

  $('#my_dtp').datetimepicker({
  format: 'dd-mm-yyyy',
                    startView: '2',
                    minView: '2',
                    autoclose: true,
                    initialDate: '02-10-2017',
                    endDate: '08-01-2018',
                    daysOfWeekDisabled: '[0,2,3,4,5,6]',
})

**Comment by AuspeXeu** [comment]
Your fiddle is different to your code in the issue... please fix

**Comment by pratyushdhanuka** [comment]
Updated the fiddle, sorry for the confusion

**Comment by AuspeXeu** [comment]
Try removing the quotes around the array

`daysOfWeekDisabled: [0,2,3,4,5,6]`

**Comment by pratyushdhanuka** [comment]
thnx, this worked for me
