### ISSUE TITLE
Calendar View always moving to decade view

### ISSUE THREAD

**Issue by pratyushdhanuka** [AuspeXeu/bootstrap-datetimepicker#7]
Hi
If i set the `startView` then the fist calendar view is coming correctly
but then if I want to move a level higher, I click the top date button and its always moving it to decade view,
the correct flow should be from 
- hour to day, 
- day to month, 
- month to year, 
- year to decade
but it always goes to decade view

Fiddle : https://jsfiddle.net/sqwwcjzu/39/
I have 4 samples prepared to verify
each starting from different View, in all upon clicking the top date button to move a level higher
we go highest level instead, 
I have verified its only happening when we set the start view,

**Comment by AuspeXeu** [comment]
It seems to have to do something with this line ... in case you have time to investigate further.

https://github.com/AuspeXeu/bootstrap-datetimepicker/blob/master/js/bootstrap-datetimepicker.js#L1022

**Comment by pratyushdhanuka** [comment]
I can look into it, 
just to confirm the expected behavior should be to move the calendar view one level up/down at a time

**Comment by AuspeXeu** [comment]
Closed due to inactivity
