### ISSUE TITLE
locale does not switch

### ISSUE THREAD

**Issue by alexey** [AuspeXeu/bootstrap-datetimepicker#8]
Hi,

I tried both loading locale file before(and after) datetimepicker and by create locale before/after.. it does not switch in any way..
What i am doing wrong ?
https://jsfiddle.net/sqwwcjzu/41/

please help

**Comment by AuspeXeu** [comment]
Correct option name is `language`

```
$('#my_dtp').datetimepicker({
  autoclose: true,
  todayBtn: false,
  startDate: '+2d',
  endDate: '+3m',
  todayHighlight: false,
  minuteStep: 5,
  language: 'he',
  pickerPosition: "bottom-center"
});
```
